"""empty message

Revision ID: 671353e4a915
Revises: 997457485e61
Create Date: 2020-04-12 23:37:53.542585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '671353e4a915'
down_revision = '997457485e61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'user', sa.Column('location', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'location', ['location'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column(u'user', 'location')
    op.drop_table('location')
    # ### end Alembic commands ###
